from __future__ import annotations

import logging

from app.db.oracle import Oracle, is_ora_error

log = logging.getLogger(__name__)


DDL_STATEMENTS = [
    """
    CREATE TABLE raw_messages (
      message_id    VARCHAR2(128) PRIMARY KEY,
      group_id      VARCHAR2(128) NOT NULL,
      ts            NUMBER(19) NOT NULL,
      sender_hash   VARCHAR2(64) NOT NULL,
      content_text  CLOB,
      image_paths_json CLOB,
      reply_to_id   VARCHAR2(128),
      created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE buffers (
      group_id     VARCHAR2(128) PRIMARY KEY,
      buffer_text  CLOB,
      updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
    """,
    """
    CREATE TABLE cases (
      case_id          VARCHAR2(32) PRIMARY KEY,
      group_id         VARCHAR2(128) NOT NULL,
      status           VARCHAR2(16) NOT NULL,
      problem_title    VARCHAR2(256) NOT NULL,
      problem_summary  CLOB NOT NULL,
      solution_summary CLOB,
      tags_json        CLOB,
      evidence_image_paths_json CLOB,
      created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT cases_status_chk CHECK (status IN ('solved', 'open'))
    )
    """,
    """
    CREATE TABLE case_evidence (
      case_id    VARCHAR2(32) NOT NULL,
      message_id VARCHAR2(128) NOT NULL,
      PRIMARY KEY (case_id, message_id)
    )
    """,
    """
    CREATE TABLE admins_groups (
      admin_id   VARCHAR2(128) NOT NULL,
      group_id   VARCHAR2(128) NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      PRIMARY KEY (admin_id, group_id)
    )
    """,
    """
    CREATE TABLE history_tokens (
      token       VARCHAR2(64) PRIMARY KEY,
      admin_id    VARCHAR2(128) NOT NULL,
      group_id    VARCHAR2(128) NOT NULL,
      expires_at  TIMESTAMP NOT NULL,
      used_at     TIMESTAMP
    )
    """,
    """
    CREATE TABLE jobs (
      job_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      type         VARCHAR2(64) NOT NULL,
      payload_json CLOB,
      status       VARCHAR2(16) NOT NULL,
      attempts     NUMBER DEFAULT 0 NOT NULL,
      updated_at   TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT jobs_status_chk CHECK (status IN ('pending', 'in_progress', 'done', 'failed'))
    )
    """,
]


def ensure_schema(db: Oracle) -> None:
    with db.connection() as conn:
        cur = conn.cursor()
        for ddl in DDL_STATEMENTS:
            try:
                cur.execute(ddl)
                conn.commit()
            except Exception as exc:
                # ORA-00955: name is already used by an existing object
                if is_ora_error(exc, 955):
                    conn.rollback()
                    continue
                conn.rollback()
                log.exception("Schema DDL failed")
                raise

